CREATE INDEX location_idx ON festival (location_id);
CREATE INDEX equipment_idx ON  equipment(equipmentCategory_category);
CREATE INDEX equipment_used_idx ON  equipmentUsed(equipment_id);
CREATE INDEX equipment_used_stage_idx ON equipmentUsed(stage_id);
CREATE INDEX festival_idx ON music_event(festival_id);
CREATE INDEX stage_idx ON music_event(stage_id);
CREATE INDEX staff_exp_idx ON staff(staff_levels_experience_desc);
CREATE INDEX staff_role_idx ON staff(role_staff_desc);
CREATE INDEX artist_idx ON artist(artist_performer_id);
CREATE INDEX art_genre_idx ON art2genre(genre_desc);
CREATE INDEX genre_artist_idx ON art2genre(artist_id);
CREATE INDEX band_idx ON band(band_performer_id);
CREATE INDEX band_genredesc_idx ON band2genre(genre_desc);
CREATE INDEX band_genreidx ON band2genre(band_id);
CREATE INDEX memb_band_idx ON members(band_id);
CREATE INDEX memb_artist_idx ON members(artist_id);
CREATE INDEX perf_event_idx ON performance(music_event_id);
CREATE INDEX performer_idx ON performance(performer_id);
CREATE INDEX perf_type_idx ON performance(type_performance_desc);
CREATE INDEX staff_works_idx ON worksIn(staff_id);
CREATE INDEX staff_event_idx ON worksIn(music_event_id);
CREATE INDEX ticket_evnet_idx ON ticket(music_event_id);
CREATE INDEX ticket_visitor_idx ON ticket(visitor_id);
CREATE INDEX ticket_type_idx ON ticket(ticketType_type) ;
CREATE INDEX review_visitor_idx ON review(visitor_id) ;
CREATE INDEX review_performance_idx ON review(performance_id);
CREATE INDEX seller_idx ON seller(visitor_id);
CREATE INDEX selle_ticket_idx ON seller(ticket_id);
CREATE INDEX buyer_visitor_idx ON buyer(visitor_id);
CREATE INDEX buyer_event_idx ON buyer(music_event_id);
CREATE INDEX buyer_ticket_idx ON buyer(ticketType_type);

CREATE INDEX year_idx ON festival(festival_fest_year);
